version: 2.1

jobs:
    build:
        docker:
            - image: cimg/node:19.7.0
        steps:
            - checkout
            - run:
                  name: Update NPM
                  command: sudo npm install -g npm@9.5.0
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                  name: Install Dependencies
                  command: npm ci
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: Build React App
                  command: npm run build
            - persist_to_workspace:
                  root: ./
                  paths:
                      - ./node_modules/
                      - ./build/
    test:
        docker:
            - image: cimg/node:19.7.0
        steps:
            - checkout:
                  path: ./
            - attach_workspace:
                  at: ./
            - run: npm run test
    deploy:
        docker:
            - image: google/cloud-sdk:latest
        steps:
            - checkout:
                  path: ./
            - attach_workspace:
                  at: ./
            - run:
                  name: Authenticate service account
                  command: |
                      echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
                      gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            - run:
                  name: 'Deploy app'
                  command: gcloud app deploy

workflows:
    build-test-deploy:
        jobs:
            - build
            - test:
                  requires:
                      - build
            - deploy:
                  requires:
                      - test
                  filters:
                      branches:
                          only: main
